### ISSUE TITLE
back-cover - loose lip in model

### ISSUE THREAD

**Issue by Minkynl** [bq/ciclop#10]
Hi,

I just checked the Freecad and Step versions of this file and the lid has a separate lip on one side (support) while the one on the other side is attached. Is that correct?

Best regards,
Ming-Hua

**Comment by Jesus89** [comment]
Hi, this is a little bug. We will fix it soon.
Thanks!

**Comment by Jesus89** [comment]
Solved in 691fda5ed3d4b29b05e06f23319fbd992fde2c44
