### ISSUE TITLE
Backlash between disk holder and shaft coupling

### ISSUE THREAD

**Issue by f3nix** [bq/ciclop#12]
Hi,
there is ~0,4mm backlash between disk holder and shaft coupling. Does it have impact on scanning precision?

Cheers,
Mateusz

**Comment by Jesus89** [comment]
Hi. We have tested experimentally these pieces and good results have been obtained. This depends on your printer quality. Btw, if you have no space between the pieces the motor will assume the object weight. Because of that, some little space is needed.
