### ISSUE TITLE
Hello,I am interested in your device!

### ISSUE THREAD

**Issue by a312514554** [bq/ciclop#7]
Hello, I am interested in your device, I am a student in Wuhan university of technology, China. My major is reverse engineering, and I just want to buy the device for my interests including the circuits, software,mechanical structure(all the devices) . Could you help me? If you will, how much is it?Thank you for your help! I will be looking forward to your reply!

**Comment by Jesus89** [comment]
https://github.com/bq/horus/issues/9

;)
