### ISSUE TITLE
Disc holder missing nut capture points

### ISSUE THREAD

**Issue by DaveyRance** [bq/ciclop#8]
Hi there i have just noticed that the disk holder picture in the exploded parts shows that it should have a captured M8 Nut so the bearing can be clamped.  It seems that the current disk holder dose not have this.

**Comment by Jesus89** [comment]
Hi. We have improved this part, removing the three M8 nuts and doing threads in the methacrylate disc. Here you have the updated post: http://diwo.bq.com/en/ciclop-released.
